// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS2-SDWYkBO1GXh7_GNPuuslWv0rRalMY',
    appId: '1:611000807309:web:f01a936d32cb45c83417c4',
    messagingSenderId: '611000807309',
    projectId: 'fixaxi',
    authDomain: 'fixaxi.firebaseapp.com',
    storageBucket: 'fixaxi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0GohI-X9C8wFg08eVFchymE1z3ig91o',
    appId: '1:611000807309:android:9f5bdc088d75c2053417c4',
    messagingSenderId: '611000807309',
    projectId: 'fixaxi',
    storageBucket: 'fixaxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Y-eMGnCJvKXywQu-myQMWlHzAAX9mF4',
    appId: '1:611000807309:ios:d98232627e014d9d3417c4',
    messagingSenderId: '611000807309',
    projectId: 'fixaxi',
    storageBucket: 'fixaxi.appspot.com',
    iosBundleId: 'com.example.fixaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Y-eMGnCJvKXywQu-myQMWlHzAAX9mF4',
    appId: '1:611000807309:ios:d98232627e014d9d3417c4',
    messagingSenderId: '611000807309',
    projectId: 'fixaxi',
    storageBucket: 'fixaxi.appspot.com',
    iosBundleId: 'com.example.fixaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS2-SDWYkBO1GXh7_GNPuuslWv0rRalMY',
    appId: '1:611000807309:web:eb66ebce06a1a1cc3417c4',
    messagingSenderId: '611000807309',
    projectId: 'fixaxi',
    authDomain: 'fixaxi.firebaseapp.com',
    storageBucket: 'fixaxi.appspot.com',
  );

}